#' Build home page
#'
#' First looks for `index.Rmd` or `README.Rmd`, then
#' `index.md` or `README.md`. If none are found, falls back to the
#' description field in `DESCRIPTION`.
#'
#' @section YAML config:
#' To tweak the home page, you need a section called `home`.
#'
#' The sidebar links are automatically generated by inspecting the
#' `URL` and `BugReports` fields of the `DESCRIPTION`.
#' You can add additional links with a subsection called `links`,
#' which should contain a list of `text` + `href` elements:
#'
#' \preformatted{
#' home:
#'   links:
#'   - text: Link text
#'     href: http://website.com
#' }
#'
#' The "developers" list is populated by the maintainer ("cre"), authors
#' ("aut"), and funder ("fnd").
#'
#' @section Badges:
#' Status badges are displayed in the sidebar under the section "Dev status".
#' This section is automatically populated if the first paragraph of the
#' homepage consists solely of status badges as linked images.
#'
#' @inheritParams build_articles
#' @export
build_home <- function(pkg = ".",
                       path = "docs",
                       depth = 0L,
                       encoding = "UTF-8",
                       preview = NA) {

  pkg <- section_init(pkg, depth = depth)
  path <- rel_path(path, pkg$path)
  rule("Building home")


  if (has_citation(pkg$path)) {
    build_citation_authors(pkg, path = path, depth = depth)
  } else {
    build_authors(pkg, path = path, depth = depth)
  }
  build_home_md(pkg, path, depth = depth)
  build_home_license(pkg, path)
  build_home_index(pkg, path, depth = depth, encoding = encoding)

  section_fin(path, preview = preview)
}
