#' Build complete static documentation for a package.
#'
#' Currently, knitr builds documentation for:
#'
#' \itemize{
#'   \item Rd files.  Files
#'   \item Demos. Must be listed in \file{demos/00index}.
#'   \item Vignettes.
#' }
#'
#' @param package path to source version of package.  See
#'   \code{\link[devtools]{as.package}} for details on how paths and package
#'   names are resolved.
#' @param base_path root directory in which to create documentation
#' @param examples include examples or not?  Examples are particularly
#'   slow to render because all code must be run, so turning them off makes
#'   it easier to tweak templates etc.
#' @export
#' @import stringr
#' @importFrom devtools load_all
#' @aliases staticdocs-package
build_package <- function(package, base_path = NULL, examples = NULL) {
  load_all(package)
  
  package <- package_info(package, base_path, examples)
  if (!file.exists(package$base_path)) dir.create(package$base_path)
  copy_bootstrap(base_path)

  # reset headlinks
  add_headlink(NULL)
  
  package$topics <- build_topics(package)
  package$vignettes <- build_vignettes(package)
  package$demos <- build_demos(package)
  package$readme <- readme(package)
  build_references(package)
  package$citation <- build_citation(package)
  
  build_index(package)
  
  # render main pages
  build_pages(package)
  
  if (interactive()) {
    browseURL(normalizePath(file.path(base_path, "index.html")))
  }
  invisible(TRUE)
}


#' Generate all topic pages for a package.
#'
#' @export
#' @inheritParams build_package
#' @param package_info A list containing information about the package,
#'   as generated by \code{\link{package_info}}
#' @keywords internal
build_topics <- function(package) {

  # for each file, find name of one topic
  index <- package$rd_index
  paths <- file.path(package$base_path, index$file_out)

  # create columns for extra topic info
  index$title <- ""
  index$in_index <- TRUE
  
  for (i in seq_along(index$name)) {
    message("Generating ", basename(paths[[i]]))
    
    rd <- package$rd[[i]]
    html <- to_html(rd, 
      env = new.env(parent = globalenv()), 
      topic = str_replace(basename(paths[[i]]), "\\.html$", ""),
      package = package)

    html$package <- package$package
    render_template("topic", html, paths[[i]])
    graphics.off()

    if ("internal" %in% html$keywords) {
      index$in_index[i] <- FALSE
    }
    index$title[i] <- html$title
  }

  index
}

readme <- function(package) {
  if (!is.null(package$readme)) return(markdown(package$readme))
  
  path <- file.path(package$path, "README.md")
  # use description if no README.md is available
  if (!file.exists(path)) return( package$description )
  
  markdown(path = path)
}

copy_bootstrap <- function(base_path) {
  bootstrap <- file.path(inst_path(), "bootstrap")
  file.copy(dir(bootstrap, full.names = TRUE), base_path, recursive = TRUE)
}


#' List all package vignettes.
#'
#' Copies all vignettes and returns data structure suitable for use with
#' whisker templates.
#'
#' @keywords internal
#' @inheritParams build_package
#' @importFrom tools buildVignettes
#' @return a list, with one element for each vignette containing the vignette
#'   title and file name.
build_vignettes <- function(package) {  
  # Locate source and built versions of vignettes
  path <- dir(file.path(package$path, c("inst/doc", "vignettes")), ".Rnw", 
    full.names = TRUE)
  if (length(path) == 0) return()
  
  message("Building vignettes")
  buildVignettes(dir = package$path)
  
  message("Copying vignettes")
  src <- str_replace(path, "\\.Rnw$", ".pdf")
  filename <- basename(src)
  dest <- file.path(package$base_path, "vignettes")

  if (!file.exists(dest)) dir.create(dest)
  file.copy(src, file.path(dest, filename))  

  # Extract titles
  title <- vapply(path, FUN.VALUE = character(1), function(x) {
    contents <- str_c(readLines(x), collapse = "\n")
    str_match(contents, "\\\\VignetteIndexEntry\\{(.*?)\\}")[2]
  })  
  
  list(vignette=unname(apply(cbind(filename, title), 1, as.list)))
}

#' Creates a Bibliography Page
#' 
#' @param package package name or object
#' @param base_path output path. If missing it is taken from \code{package}
#' 
#' @keywords internal
#' @importFrom bibtex read.bib
build_references <- function(package, base_path=NULL){
	
	# pre-process arguments
	package <- package_info(package, base_path=base_path)
	
	# look for reference file in inst/
	ref <- inst_path('REFERENCES.bib', package=package)
	if( !file.exists(ref) ) return()
	
	outfile <- file.path(package$base_path, '_REFERENCES.html') 
	message("Generating ", basename(outfile))
	# load bibtex items
	bibs <- read.bib(ref)
	# format
	package$references <- lapply(format(bibs, style='html'), function(x) list(bibitems=x))
	
	# render dedicated file
	render_template("index-references", package, outfile)
	# add dedicated head link
	add_headlink(package, basename(outfile), 'References')

}

capfirst <- function(s) {
	paste(toupper(substring(s,1,1)), tolower(substring(s,2)), sep='')
}

#' @importFrom utils readCitationFile
build_citation <- function(package){
  citfile <- inst_path('CITATION', package = package)
  if( !file.exists(citfile) ) return()
  message('Rendering CITATION')
  package[capfirst(names(package))] <- package
  cit <- readCitationFile(citfile, meta = package)
  # only extract first one
  gsub("(^<p>)|(</p>$)", "", format(cit[[1L]], style = 'html'))
}

build_demos <- function(package, index, base_path=NULL) {
  # pre-process arguments
  package <- package_info(package, base_path=base_path)
	
  demo_dir <- file.path(package$path, "demo")
  if (!file.exists(demo_dir)) return()
  
  message("Rendering demos")
  demos <- readLines(file.path(demo_dir, "00Index"))
  
  pieces <- str_split_fixed(demos, "\\s+", 2)
  in_path <- str_c(pieces[, 1], ".r")
  filename <- str_c("demo-", pieces[,1], ".html")
  title <- pieces[, 2]
  
  for(i in seq_along(title)) {
    demo_code <- readLines(file.path(demo_dir, in_path[i]))
    demo_expr <- evaluate(demo_code, new.env(parent = globalenv()))

    package$demo <- replay_html(demo_expr,
      package = package, 
      name = str_c(pieces[i], "-"))
    package$title <- title[i]
    render_template("demo", package, 
      file.path(package$base_path, filename[i]))
  }
  
  package$demos <- list(demo=unname(apply(cbind(filename, title), 1, as.list)))
  
  # render dedicated file
  outfile <- file.path(package$base_path, '_DEMOS.html')
  message("Generating ", basename(outfile))
  render_template("index-demos", package, outfile)
  # add dedicated head link
  add_headlink(package, basename(outfile), 'Demos')
  
  # return updated package
  package$demos
}

# wrap a content into the main layout
wrap_page <- local({
	.cache <- NULL
	function(package, file, layout='layout'){
		if( is.null(package) ){ # reset cache
			.cache <<- NULL
			return()
		}
		
		# append prefix 'layout-' if necessary
		if( !grepl("^layout", layout) ) layout <- str_c('layout-', layout)
		
		# render template once
		if( is.null(.cache) ){
			lpackage <- package
			# escape tag {{{contents}}}
			lpackage$contents <- "{{{contents}}}"
			lpackage$headlinks <- add_headlink()
			# generate navigation bar
			lpackage$navbar <- paste(capture.output(render_template("navbar", lpackage)), collapse="\n")
			# render outer layout
			.cache <<- capture.output(render_template(layout, lpackage))
		}
				
		sapply(file, function(f){
			# collapse contents
			contents <- paste(readLines(f, warn=FALSE), collapse="\n")
			# substitute in layout template
			rendered <- whisker.render(.cache, list(contents=contents))
			cat(rendered, file = f)
		})
		invisible()
	}
})

add_headlink <- local({
	
	.cache <- NULL
	function(package, target, face=target, prepend=FALSE){
		
		if( missing(package) ){
			return( .cache ) 
		}
		if( is.null(package) ){ # reset cache
			.cache <<- NULL
			return()
		}
		
		if( is.null(face) ) face <- target
		.cache <<-
		if( !prepend ){
			c(.cache, list(list(target=target, face=face)))
		}else{
			c(list(list(target=target, face=face)), .cache)
		}
		.cache
	}
})

# Adds Navigation Bar
build_pages <- function(package, base_path=NULL, layout='default') {
	
  # pre-process arguments
  package <- package_info(package, base_path=base_path)
  outpath <- package$base_path
  
  wrap_page(NULL)
  # substitute head links in all html files starting with '_'
  files <- dir(outpath, pattern="^_.*\\.html", full.names=TRUE)
  files <- c(file.path(outpath,'index.html'), files)
  message("Wrapping pages in layout:", layout)
  wrap_page(package, files, layout=layout)
	
}
